# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x08tasklist\"6\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\x14\n\x06TaskId\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x12\x44\x65leteTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xd4\x01\n\x0bTaskService\x12,\n\nCreateTask\x12\x0e.tasklist.Task\x1a\x0e.tasklist.Task\x12+\n\x07GetTask\x12\x10.tasklist.TaskId\x1a\x0e.tasklist.Task\x12,\n\nUpdateTask\x12\x0e.tasklist.Task\x1a\x0e.tasklist.Task\x12<\n\nDeleteTask\x12\x10.tasklist.TaskId\x1a\x1c.tasklist.DeleteTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASK']._serialized_start=25
  _globals['_TASK']._serialized_end=79
  _globals['_TASKID']._serialized_start=81
  _globals['_TASKID']._serialized_end=101
  _globals['_DELETETASKRESPONSE']._serialized_start=103
  _globals['_DELETETASKRESPONSE']._serialized_end=140
  _globals['_TASKSERVICE']._serialized_start=143
  _globals['_TASKSERVICE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
